# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-29 06:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('mobile', models.CharField(help_text='start with 254xxxxxxxx', max_length=12)),
                ('id_number', models.CharField(max_length=8)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('last_name', 'first_name'),
                'db_table': 'sph_contacts',
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
            },
        ),
        migrations.CreateModel(
            name='Contact_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
                'db_table': 'sph_groups',
                'verbose_name': 'group',
                'verbose_name_plural': 'groups',
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Contact_Group'),
        ),
        migrations.AddField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='contact_group',
            unique_together=set([('user', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together=set([('user', 'mobile', 'id_number')]),
        ),
    ]
