# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-15 20:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('full_name',), 'verbose_name': 'contact', 'verbose_name_plural': 'contacts'},
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='last_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='first_name',
        ),
    ]
