# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-26 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='mobile',
            field=models.CharField(help_text='start with 254xxxxxxxx', max_length=12, unique=True),
        ),
    ]
