# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-23 23:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20170524_0158'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contact',
            table='sph_contacts',
        ),
        migrations.AlterModelTable(
            name='contact_group',
            table='sph_contact_groups',
        ),
    ]
