# Generated by Django 2.1.5 on 2019-08-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20180215_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='mobile',
            field=models.CharField(help_text='start with 254xxxxxxxx', max_length=13),
        ),
    ]
