# Generated by Django 2.2.4 on 2019-08-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20190827_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='category',
        ),
        migrations.AddField(
            model_name='contact',
            name='category',
            field=models.ManyToManyField(to='contacts.Contact_Group'),
        ),
    ]
