# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-08 00:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20170607_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='id_number',
        ),
    ]
