# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-15 20:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='public_email',
        ),
    ]
