# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-23 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('sph_messages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sms',
            name='to',
        ),
        migrations.AddField(
            model_name='sms',
            name='to',
            field=models.ManyToManyField(to='contacts.Contact', verbose_name='contacts'),
        ),
    ]
