# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 1980-01-05 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sph_messages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smssettings',
            name='user',
        ),
        migrations.AddField(
            model_name='sms',
            name='to',
            field=models.CharField(blank=True, max_length=13000, null=True),
        ),
        migrations.DeleteModel(
            name='SmsSettings',
        ),
    ]
