# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-26 20:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sph_messages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sms',
            old_name='numbers',
            new_name='category',
        ),
    ]
