# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-07 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sph_messages', '0002_auto_19800105_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='to',
            field=models.CharField(blank=True, editable=False, max_length=13000, null=True),
        ),
    ]
