# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-23 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sph_messages', '0002_auto_20170523_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sms',
            name='to',
        ),
        migrations.AddField(
            model_name='sms',
            name='to',
            field=models.CharField(default=123456789, max_length=1040),
        ),
    ]
