# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-23 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sph_messages', '0003_auto_20170523_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='to',
            field=models.CharField(max_length=1040),
        ),
    ]
