# Generated by Django 2.1.5 on 2019-08-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='messageId',
            field=models.CharField(max_length=256),
        ),
    ]
