# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-18 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sms',
            name='recipient_count',
        ),
        migrations.RemoveField(
            model_name='sms',
            name='recipient_list',
        ),
        migrations.AddField(
            model_name='sms',
            name='cost',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='sms',
            name='messageId',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sms',
            name='number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='sms',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
