# Generated by Django 2.1.5 on 2019-08-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgs', '0002_auto_20190827_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='cost',
            field=models.CharField(max_length=100),
        ),
    ]
