# Generated by Django 2.2.4 on 2019-08-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20190829_1826'),
        ('msgs', '0003_auto_20190827_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sms',
            name='category',
        ),
        migrations.AddField(
            model_name='sms',
            name='category',
            field=models.ManyToManyField(to='contacts.Contact_Group'),
        ),
    ]
